// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DataCenter.proto

package DataCenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginType int32

const (
	LoginType_UNUSE   LoginType = 0
	LoginType_TEACHER LoginType = 10001
	LoginType_STUDENT LoginType = 10002
	LoginType_ADMIN   LoginType = 10003
)

var LoginType_name = map[int32]string{
	0:     "UNUSE",
	10001: "TEACHER",
	10002: "STUDENT",
	10003: "ADMIN",
}

var LoginType_value = map[string]int32{
	"UNUSE":   0,
	"TEACHER": 10001,
	"STUDENT": 10002,
	"ADMIN":   10003,
}

func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}

func (LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{0}
}

type StudentInfo_STATUS int32

const (
	StudentInfo_NORMEAL StudentInfo_STATUS = 0
	StudentInfo_LEAVE   StudentInfo_STATUS = 1
)

var StudentInfo_STATUS_name = map[int32]string{
	0: "NORMEAL",
	1: "LEAVE",
}

var StudentInfo_STATUS_value = map[string]int32{
	"NORMEAL": 0,
	"LEAVE":   1,
}

func (x StudentInfo_STATUS) String() string {
	return proto.EnumName(StudentInfo_STATUS_name, int32(x))
}

func (StudentInfo_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{1, 0}
}

type TeacherInfo_STATUS int32

const (
	TeacherInfo_NORMAL TeacherInfo_STATUS = 0
	TeacherInfo_LEAVE  TeacherInfo_STATUS = 1
)

var TeacherInfo_STATUS_name = map[int32]string{
	0: "NORMAL",
	1: "LEAVE",
}

var TeacherInfo_STATUS_value = map[string]int32{
	"NORMAL": 0,
	"LEAVE":  1,
}

func (x TeacherInfo_STATUS) String() string {
	return proto.EnumName(TeacherInfo_STATUS_name, int32(x))
}

func (TeacherInfo_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{2, 0}
}

type CourseInfo_STATUS int32

const (
	CourseInfo_PLAN  CourseInfo_STATUS = 0
	CourseInfo_DOING CourseInfo_STATUS = 1
	CourseInfo_DONE  CourseInfo_STATUS = 2
)

var CourseInfo_STATUS_name = map[int32]string{
	0: "PLAN",
	1: "DOING",
	2: "DONE",
}

var CourseInfo_STATUS_value = map[string]int32{
	"PLAN":  0,
	"DOING": 1,
	"DONE":  2,
}

func (x CourseInfo_STATUS) String() string {
	return proto.EnumName(CourseInfo_STATUS_name, int32(x))
}

func (CourseInfo_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{6, 0}
}

type ScoreInfo_STATUS int32

const (
	ScoreInfo_UNDONE ScoreInfo_STATUS = 0
	ScoreInfo_DONE   ScoreInfo_STATUS = 1
)

var ScoreInfo_STATUS_name = map[int32]string{
	0: "UNDONE",
	1: "DONE",
}

var ScoreInfo_STATUS_value = map[string]int32{
	"UNDONE": 0,
	"DONE":   1,
}

func (x ScoreInfo_STATUS) String() string {
	return proto.EnumName(ScoreInfo_STATUS_name, int32(x))
}

func (ScoreInfo_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{7, 0}
}

type AdminInfo struct {
	User                 string    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Password             string    `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Mail                 string    `protobuf:"bytes,3,opt,name=Mail,proto3" json:"Mail,omitempty"`
	CreateTime           int32     `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	ExprTime             int32     `protobuf:"varint,5,opt,name=ExprTime,proto3" json:"ExprTime,omitempty"`
	LoginIP              string    `protobuf:"bytes,6,opt,name=LoginIP,proto3" json:"LoginIP,omitempty"`
	LType                LoginType `protobuf:"varint,7,opt,name=LType,proto3,enum=DataCenter.LoginType" json:"LType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AdminInfo) Reset()         { *m = AdminInfo{} }
func (m *AdminInfo) String() string { return proto.CompactTextString(m) }
func (*AdminInfo) ProtoMessage()    {}
func (*AdminInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{0}
}

func (m *AdminInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminInfo.Unmarshal(m, b)
}
func (m *AdminInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminInfo.Marshal(b, m, deterministic)
}
func (m *AdminInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminInfo.Merge(m, src)
}
func (m *AdminInfo) XXX_Size() int {
	return xxx_messageInfo_AdminInfo.Size(m)
}
func (m *AdminInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AdminInfo proto.InternalMessageInfo

func (m *AdminInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AdminInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AdminInfo) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *AdminInfo) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *AdminInfo) GetExprTime() int32 {
	if m != nil {
		return m.ExprTime
	}
	return 0
}

func (m *AdminInfo) GetLoginIP() string {
	if m != nil {
		return m.LoginIP
	}
	return ""
}

func (m *AdminInfo) GetLType() LoginType {
	if m != nil {
		return m.LType
	}
	return LoginType_UNUSE
}

type StudentInfo struct {
	StudentUid           uint64             `protobuf:"varint,1,opt,name=StudentUid,proto3" json:"StudentUid,omitempty"`
	Password             string             `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	CollegeUid           uint64             `protobuf:"varint,3,opt,name=CollegeUid,proto3" json:"CollegeUid,omitempty"`
	MajorUid             uint64             `protobuf:"varint,4,opt,name=MajorUid,proto3" json:"MajorUid,omitempty"`
	ClassUid             uint64             `protobuf:"varint,5,opt,name=ClassUid,proto3" json:"ClassUid,omitempty"`
	Name                 string             `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	Sex                  string             `protobuf:"bytes,7,opt,name=Sex,proto3" json:"Sex,omitempty"`
	NRIC                 string             `protobuf:"bytes,8,opt,name=NRIC,proto3" json:"NRIC,omitempty"`
	Status               StudentInfo_STATUS `protobuf:"varint,9,opt,name=Status,proto3,enum=DataCenter.StudentInfo_STATUS" json:"Status,omitempty"`
	CreateTime           int32              `protobuf:"varint,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	LType                LoginType          `protobuf:"varint,11,opt,name=LType,proto3,enum=DataCenter.LoginType" json:"LType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StudentInfo) Reset()         { *m = StudentInfo{} }
func (m *StudentInfo) String() string { return proto.CompactTextString(m) }
func (*StudentInfo) ProtoMessage()    {}
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{1}
}

func (m *StudentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentInfo.Unmarshal(m, b)
}
func (m *StudentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentInfo.Marshal(b, m, deterministic)
}
func (m *StudentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentInfo.Merge(m, src)
}
func (m *StudentInfo) XXX_Size() int {
	return xxx_messageInfo_StudentInfo.Size(m)
}
func (m *StudentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StudentInfo proto.InternalMessageInfo

func (m *StudentInfo) GetStudentUid() uint64 {
	if m != nil {
		return m.StudentUid
	}
	return 0
}

func (m *StudentInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *StudentInfo) GetCollegeUid() uint64 {
	if m != nil {
		return m.CollegeUid
	}
	return 0
}

func (m *StudentInfo) GetMajorUid() uint64 {
	if m != nil {
		return m.MajorUid
	}
	return 0
}

func (m *StudentInfo) GetClassUid() uint64 {
	if m != nil {
		return m.ClassUid
	}
	return 0
}

func (m *StudentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *StudentInfo) GetNRIC() string {
	if m != nil {
		return m.NRIC
	}
	return ""
}

func (m *StudentInfo) GetStatus() StudentInfo_STATUS {
	if m != nil {
		return m.Status
	}
	return StudentInfo_NORMEAL
}

func (m *StudentInfo) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *StudentInfo) GetLType() LoginType {
	if m != nil {
		return m.LType
	}
	return LoginType_UNUSE
}

type TeacherInfo struct {
	TeacherUid           uint64             `protobuf:"varint,1,opt,name=TeacherUid,proto3" json:"TeacherUid,omitempty"`
	Password             string             `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	CollegeUid           uint64             `protobuf:"varint,3,opt,name=CollegeUid,proto3" json:"CollegeUid,omitempty"`
	String_              string             `protobuf:"bytes,4,opt,name=string,proto3" json:"string,omitempty"`
	Sex                  string             `protobuf:"bytes,5,opt,name=Sex,proto3" json:"Sex,omitempty"`
	NRIC                 string             `protobuf:"bytes,6,opt,name=NRIC,proto3" json:"NRIC,omitempty"`
	Status               TeacherInfo_STATUS `protobuf:"varint,7,opt,name=Status,proto3,enum=DataCenter.TeacherInfo_STATUS" json:"Status,omitempty"`
	CreateTime           uint32             `protobuf:"varint,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Name                 string             `protobuf:"bytes,9,opt,name=Name,proto3" json:"Name,omitempty"`
	LType                LoginType          `protobuf:"varint,10,opt,name=LType,proto3,enum=DataCenter.LoginType" json:"LType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TeacherInfo) Reset()         { *m = TeacherInfo{} }
func (m *TeacherInfo) String() string { return proto.CompactTextString(m) }
func (*TeacherInfo) ProtoMessage()    {}
func (*TeacherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{2}
}

func (m *TeacherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeacherInfo.Unmarshal(m, b)
}
func (m *TeacherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeacherInfo.Marshal(b, m, deterministic)
}
func (m *TeacherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeacherInfo.Merge(m, src)
}
func (m *TeacherInfo) XXX_Size() int {
	return xxx_messageInfo_TeacherInfo.Size(m)
}
func (m *TeacherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TeacherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TeacherInfo proto.InternalMessageInfo

func (m *TeacherInfo) GetTeacherUid() uint64 {
	if m != nil {
		return m.TeacherUid
	}
	return 0
}

func (m *TeacherInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TeacherInfo) GetCollegeUid() uint64 {
	if m != nil {
		return m.CollegeUid
	}
	return 0
}

func (m *TeacherInfo) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *TeacherInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *TeacherInfo) GetNRIC() string {
	if m != nil {
		return m.NRIC
	}
	return ""
}

func (m *TeacherInfo) GetStatus() TeacherInfo_STATUS {
	if m != nil {
		return m.Status
	}
	return TeacherInfo_NORMAL
}

func (m *TeacherInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *TeacherInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TeacherInfo) GetLType() LoginType {
	if m != nil {
		return m.LType
	}
	return LoginType_UNUSE
}

type CollegeInfo struct {
	CollegeUid           uint64   `protobuf:"varint,1,opt,name=CollegeUid,proto3" json:"CollegeUid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CreateTime           uint32   `protobuf:"varint,3,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollegeInfo) Reset()         { *m = CollegeInfo{} }
func (m *CollegeInfo) String() string { return proto.CompactTextString(m) }
func (*CollegeInfo) ProtoMessage()    {}
func (*CollegeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{3}
}

func (m *CollegeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollegeInfo.Unmarshal(m, b)
}
func (m *CollegeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollegeInfo.Marshal(b, m, deterministic)
}
func (m *CollegeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollegeInfo.Merge(m, src)
}
func (m *CollegeInfo) XXX_Size() int {
	return xxx_messageInfo_CollegeInfo.Size(m)
}
func (m *CollegeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollegeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollegeInfo proto.InternalMessageInfo

func (m *CollegeInfo) GetCollegeUid() uint64 {
	if m != nil {
		return m.CollegeUid
	}
	return 0
}

func (m *CollegeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollegeInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type MajorInfo struct {
	MajorUid             uint64   `protobuf:"varint,1,opt,name=MajorUid,proto3" json:"MajorUid,omitempty"`
	CollegeUid           uint64   `protobuf:"varint,2,opt,name=CollegeUid,proto3" json:"CollegeUid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	CreateTime           uint32   `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MajorInfo) Reset()         { *m = MajorInfo{} }
func (m *MajorInfo) String() string { return proto.CompactTextString(m) }
func (*MajorInfo) ProtoMessage()    {}
func (*MajorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{4}
}

func (m *MajorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MajorInfo.Unmarshal(m, b)
}
func (m *MajorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MajorInfo.Marshal(b, m, deterministic)
}
func (m *MajorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MajorInfo.Merge(m, src)
}
func (m *MajorInfo) XXX_Size() int {
	return xxx_messageInfo_MajorInfo.Size(m)
}
func (m *MajorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MajorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MajorInfo proto.InternalMessageInfo

func (m *MajorInfo) GetMajorUid() uint64 {
	if m != nil {
		return m.MajorUid
	}
	return 0
}

func (m *MajorInfo) GetCollegeUid() uint64 {
	if m != nil {
		return m.CollegeUid
	}
	return 0
}

func (m *MajorInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MajorInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type ClassInfo struct {
	ClassUid             uint64   `protobuf:"varint,1,opt,name=ClassUid,proto3" json:"ClassUid,omitempty"`
	MajorUid             uint64   `protobuf:"varint,2,opt,name=MajorUid,proto3" json:"MajorUid,omitempty"`
	CollegeUid           uint64   `protobuf:"varint,3,opt,name=CollegeUid,proto3" json:"CollegeUid,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	StudentNum           uint32   `protobuf:"varint,5,opt,name=StudentNum,proto3" json:"StudentNum,omitempty"`
	CreateTime           uint32   `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassInfo) Reset()         { *m = ClassInfo{} }
func (m *ClassInfo) String() string { return proto.CompactTextString(m) }
func (*ClassInfo) ProtoMessage()    {}
func (*ClassInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{5}
}

func (m *ClassInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassInfo.Unmarshal(m, b)
}
func (m *ClassInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassInfo.Marshal(b, m, deterministic)
}
func (m *ClassInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassInfo.Merge(m, src)
}
func (m *ClassInfo) XXX_Size() int {
	return xxx_messageInfo_ClassInfo.Size(m)
}
func (m *ClassInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClassInfo proto.InternalMessageInfo

func (m *ClassInfo) GetClassUid() uint64 {
	if m != nil {
		return m.ClassUid
	}
	return 0
}

func (m *ClassInfo) GetMajorUid() uint64 {
	if m != nil {
		return m.MajorUid
	}
	return 0
}

func (m *ClassInfo) GetCollegeUid() uint64 {
	if m != nil {
		return m.CollegeUid
	}
	return 0
}

func (m *ClassInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClassInfo) GetStudentNum() uint32 {
	if m != nil {
		return m.StudentNum
	}
	return 0
}

func (m *ClassInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

// 课程表
type CourseInfo struct {
	CourseUid            uint64            `protobuf:"varint,1,opt,name=CourseUid,proto3" json:"CourseUid,omitempty"`
	CollegeUid           uint64            `protobuf:"varint,2,opt,name=CollegeUid,proto3" json:"CollegeUid,omitempty"`
	Name                 string            `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Credit               float32           `protobuf:"fixed32,4,opt,name=Credit,proto3" json:"Credit,omitempty"`
	Hour                 float32           `protobuf:"fixed32,5,opt,name=Hour,proto3" json:"Hour,omitempty"`
	Status               CourseInfo_STATUS `protobuf:"varint,6,opt,name=Status,proto3,enum=DataCenter.CourseInfo_STATUS" json:"Status,omitempty"`
	CreateTime           uint32            `protobuf:"varint,7,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Type                 int32             `protobuf:"varint,8,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CourseInfo) Reset()         { *m = CourseInfo{} }
func (m *CourseInfo) String() string { return proto.CompactTextString(m) }
func (*CourseInfo) ProtoMessage()    {}
func (*CourseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{6}
}

func (m *CourseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseInfo.Unmarshal(m, b)
}
func (m *CourseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseInfo.Marshal(b, m, deterministic)
}
func (m *CourseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseInfo.Merge(m, src)
}
func (m *CourseInfo) XXX_Size() int {
	return xxx_messageInfo_CourseInfo.Size(m)
}
func (m *CourseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CourseInfo proto.InternalMessageInfo

func (m *CourseInfo) GetCourseUid() uint64 {
	if m != nil {
		return m.CourseUid
	}
	return 0
}

func (m *CourseInfo) GetCollegeUid() uint64 {
	if m != nil {
		return m.CollegeUid
	}
	return 0
}

func (m *CourseInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CourseInfo) GetCredit() float32 {
	if m != nil {
		return m.Credit
	}
	return 0
}

func (m *CourseInfo) GetHour() float32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *CourseInfo) GetStatus() CourseInfo_STATUS {
	if m != nil {
		return m.Status
	}
	return CourseInfo_PLAN
}

func (m *CourseInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *CourseInfo) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

// 成绩信息
type ScoreInfo struct {
	ScoreUid             uint64           `protobuf:"varint,1,opt,name=ScoreUid,proto3" json:"ScoreUid,omitempty"`
	StudentUid           uint64           `protobuf:"varint,2,opt,name=StudentUid,proto3" json:"StudentUid,omitempty"`
	CourseUid            uint64           `protobuf:"varint,3,opt,name=CourseUid,proto3" json:"CourseUid,omitempty"`
	MidtermScore         float32          `protobuf:"fixed32,4,opt,name=MidtermScore,proto3" json:"MidtermScore,omitempty"`
	EndtermScore         float32          `protobuf:"fixed32,5,opt,name=EndtermScore,proto3" json:"EndtermScore,omitempty"`
	UsualScore           float32          `protobuf:"fixed32,6,opt,name=UsualScore,proto3" json:"UsualScore,omitempty"`
	Credit               float32          `protobuf:"fixed32,7,opt,name=Credit,proto3" json:"Credit,omitempty"`
	AcademicCredit       float32          `protobuf:"fixed32,8,opt,name=AcademicCredit,proto3" json:"AcademicCredit,omitempty"`
	Status               ScoreInfo_STATUS `protobuf:"varint,9,opt,name=Status,proto3,enum=DataCenter.ScoreInfo_STATUS" json:"Status,omitempty"`
	CreateTime           uint32           `protobuf:"varint,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScoreInfo) Reset()         { *m = ScoreInfo{} }
func (m *ScoreInfo) String() string { return proto.CompactTextString(m) }
func (*ScoreInfo) ProtoMessage()    {}
func (*ScoreInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{7}
}

func (m *ScoreInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreInfo.Unmarshal(m, b)
}
func (m *ScoreInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreInfo.Marshal(b, m, deterministic)
}
func (m *ScoreInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreInfo.Merge(m, src)
}
func (m *ScoreInfo) XXX_Size() int {
	return xxx_messageInfo_ScoreInfo.Size(m)
}
func (m *ScoreInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreInfo proto.InternalMessageInfo

func (m *ScoreInfo) GetScoreUid() uint64 {
	if m != nil {
		return m.ScoreUid
	}
	return 0
}

func (m *ScoreInfo) GetStudentUid() uint64 {
	if m != nil {
		return m.StudentUid
	}
	return 0
}

func (m *ScoreInfo) GetCourseUid() uint64 {
	if m != nil {
		return m.CourseUid
	}
	return 0
}

func (m *ScoreInfo) GetMidtermScore() float32 {
	if m != nil {
		return m.MidtermScore
	}
	return 0
}

func (m *ScoreInfo) GetEndtermScore() float32 {
	if m != nil {
		return m.EndtermScore
	}
	return 0
}

func (m *ScoreInfo) GetUsualScore() float32 {
	if m != nil {
		return m.UsualScore
	}
	return 0
}

func (m *ScoreInfo) GetCredit() float32 {
	if m != nil {
		return m.Credit
	}
	return 0
}

func (m *ScoreInfo) GetAcademicCredit() float32 {
	if m != nil {
		return m.AcademicCredit
	}
	return 0
}

func (m *ScoreInfo) GetStatus() ScoreInfo_STATUS {
	if m != nil {
		return m.Status
	}
	return ScoreInfo_UNDONE
}

func (m *ScoreInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type StudentCourseInfo struct {
	StudentCourseUid     uint64   `protobuf:"varint,1,opt,name=StudentCourseUid,proto3" json:"StudentCourseUid,omitempty"`
	StudentUid           uint64   `protobuf:"varint,2,opt,name=StudentUid,proto3" json:"StudentUid,omitempty"`
	CourseUid            uint64   `protobuf:"varint,3,opt,name=CourseUid,proto3" json:"CourseUid,omitempty"`
	CreateTime           uint32   `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentCourseInfo) Reset()         { *m = StudentCourseInfo{} }
func (m *StudentCourseInfo) String() string { return proto.CompactTextString(m) }
func (*StudentCourseInfo) ProtoMessage()    {}
func (*StudentCourseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{8}
}

func (m *StudentCourseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentCourseInfo.Unmarshal(m, b)
}
func (m *StudentCourseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentCourseInfo.Marshal(b, m, deterministic)
}
func (m *StudentCourseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentCourseInfo.Merge(m, src)
}
func (m *StudentCourseInfo) XXX_Size() int {
	return xxx_messageInfo_StudentCourseInfo.Size(m)
}
func (m *StudentCourseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentCourseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StudentCourseInfo proto.InternalMessageInfo

func (m *StudentCourseInfo) GetStudentCourseUid() uint64 {
	if m != nil {
		return m.StudentCourseUid
	}
	return 0
}

func (m *StudentCourseInfo) GetStudentUid() uint64 {
	if m != nil {
		return m.StudentUid
	}
	return 0
}

func (m *StudentCourseInfo) GetCourseUid() uint64 {
	if m != nil {
		return m.CourseUid
	}
	return 0
}

func (m *StudentCourseInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type NoticeInfo struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Notice               string   `protobuf:"bytes,2,opt,name=Notice,proto3" json:"Notice,omitempty"`
	CreateTime           uint32   `protobuf:"varint,3,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeInfo) Reset()         { *m = NoticeInfo{} }
func (m *NoticeInfo) String() string { return proto.CompactTextString(m) }
func (*NoticeInfo) ProtoMessage()    {}
func (*NoticeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4facc8713708bae, []int{9}
}

func (m *NoticeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeInfo.Unmarshal(m, b)
}
func (m *NoticeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeInfo.Marshal(b, m, deterministic)
}
func (m *NoticeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeInfo.Merge(m, src)
}
func (m *NoticeInfo) XXX_Size() int {
	return xxx_messageInfo_NoticeInfo.Size(m)
}
func (m *NoticeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeInfo proto.InternalMessageInfo

func (m *NoticeInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NoticeInfo) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *NoticeInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("DataCenter.LoginType", LoginType_name, LoginType_value)
	proto.RegisterEnum("DataCenter.StudentInfo_STATUS", StudentInfo_STATUS_name, StudentInfo_STATUS_value)
	proto.RegisterEnum("DataCenter.TeacherInfo_STATUS", TeacherInfo_STATUS_name, TeacherInfo_STATUS_value)
	proto.RegisterEnum("DataCenter.CourseInfo_STATUS", CourseInfo_STATUS_name, CourseInfo_STATUS_value)
	proto.RegisterEnum("DataCenter.ScoreInfo_STATUS", ScoreInfo_STATUS_name, ScoreInfo_STATUS_value)
	proto.RegisterType((*AdminInfo)(nil), "DataCenter.AdminInfo")
	proto.RegisterType((*StudentInfo)(nil), "DataCenter.StudentInfo")
	proto.RegisterType((*TeacherInfo)(nil), "DataCenter.TeacherInfo")
	proto.RegisterType((*CollegeInfo)(nil), "DataCenter.CollegeInfo")
	proto.RegisterType((*MajorInfo)(nil), "DataCenter.MajorInfo")
	proto.RegisterType((*ClassInfo)(nil), "DataCenter.ClassInfo")
	proto.RegisterType((*CourseInfo)(nil), "DataCenter.CourseInfo")
	proto.RegisterType((*ScoreInfo)(nil), "DataCenter.ScoreInfo")
	proto.RegisterType((*StudentCourseInfo)(nil), "DataCenter.StudentCourseInfo")
	proto.RegisterType((*NoticeInfo)(nil), "DataCenter.NoticeInfo")
}

func init() {
	proto.RegisterFile("DataCenter.proto", fileDescriptor_d4facc8713708bae)
}

var fileDescriptor_d4facc8713708bae = []byte{
	// 818 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xcb, 0x6e, 0xd3, 0x5c,
	0x10, 0xc7, 0x6b, 0x3b, 0x76, 0xe2, 0x49, 0x5b, 0xf9, 0xb3, 0x3e, 0x2a, 0x0b, 0x95, 0x10, 0x79,
	0x01, 0x55, 0x91, 0xba, 0xe0, 0xb6, 0x44, 0xb2, 0x12, 0x8b, 0x46, 0x4a, 0xdc, 0xca, 0x17, 0x16,
	0xec, 0x4c, 0x72, 0x28, 0x46, 0x49, 0x5c, 0xd9, 0x8e, 0x28, 0x62, 0x07, 0x4f, 0x00, 0xac, 0xe1,
	0x35, 0x78, 0x0f, 0xde, 0x80, 0x37, 0x41, 0x67, 0x7c, 0xec, 0x1c, 0xdb, 0x6d, 0x5a, 0xd1, 0xdd,
	0x99, 0x8b, 0x7d, 0x66, 0x7e, 0xff, 0xf1, 0xc8, 0xa0, 0x0d, 0xc3, 0x2c, 0x1c, 0x90, 0x65, 0x46,
	0x92, 0xa3, 0xf3, 0x24, 0xce, 0x62, 0x1d, 0xd6, 0x1e, 0xf3, 0xb7, 0x00, 0xaa, 0x35, 0x5b, 0x44,
	0xcb, 0xd1, 0xf2, 0x6d, 0xac, 0xeb, 0xd0, 0x0a, 0x52, 0x92, 0x18, 0x42, 0x5f, 0x38, 0x50, 0x5d,
	0x3c, 0xeb, 0x77, 0xa1, 0x73, 0x1a, 0xa6, 0xe9, 0x87, 0x38, 0x99, 0x19, 0x22, 0xfa, 0x4b, 0x9b,
	0xe6, 0x4f, 0xc2, 0x68, 0x6e, 0x48, 0x79, 0x3e, 0x3d, 0xeb, 0x3d, 0x80, 0x41, 0x42, 0xc2, 0x8c,
	0xf8, 0xd1, 0x82, 0x18, 0xad, 0xbe, 0x70, 0x20, 0xbb, 0x9c, 0x87, 0xbe, 0xcf, 0xbe, 0x38, 0x4f,
	0x30, 0x2a, 0x63, 0xb4, 0xb4, 0x75, 0x03, 0xda, 0xe3, 0xf8, 0x2c, 0x5a, 0x8e, 0x4e, 0x0d, 0x05,
	0x5f, 0x59, 0x98, 0xfa, 0x23, 0x90, 0xc7, 0xfe, 0xc7, 0x73, 0x62, 0xb4, 0xfb, 0xc2, 0xc1, 0xee,
	0xe3, 0x3b, 0x47, 0x5c, 0x57, 0x98, 0x43, 0x83, 0x6e, 0x9e, 0x63, 0x7e, 0x96, 0xa0, 0xeb, 0x65,
	0xab, 0x19, 0x59, 0x66, 0xd8, 0x56, 0x0f, 0x80, 0x99, 0x41, 0x34, 0xc3, 0xe6, 0x5a, 0x2e, 0xe7,
	0xd9, 0xd8, 0x22, 0x6d, 0x27, 0x9e, 0xcf, 0xc9, 0x19, 0xa1, 0xcf, 0x4a, 0xf9, 0xb3, 0x6b, 0x0f,
	0x7d, 0x76, 0x12, 0xbe, 0x8f, 0x13, 0x1a, 0x6d, 0x61, 0xb4, 0xb4, 0x69, 0x6c, 0x30, 0x0f, 0xd3,
	0x94, 0xc6, 0xe4, 0x3c, 0x56, 0xd8, 0x14, 0x9d, 0x13, 0x2e, 0x08, 0xeb, 0x13, 0xcf, 0xba, 0x06,
	0x92, 0x47, 0x2e, 0xb0, 0x45, 0xd5, 0xa5, 0x47, 0xcc, 0x72, 0x47, 0x03, 0xa3, 0xc3, 0xb2, 0xdc,
	0xd1, 0x40, 0x7f, 0x0e, 0x8a, 0x97, 0x85, 0xd9, 0x2a, 0x35, 0x54, 0x64, 0xd1, 0xe3, 0x59, 0x70,
	0x6d, 0x1f, 0x79, 0xbe, 0xe5, 0x07, 0x9e, 0xcb, 0xb2, 0x6b, 0xc2, 0x40, 0x43, 0x98, 0x12, 0x71,
	0xf7, 0x06, 0x88, 0xfb, 0xa0, 0xe4, 0xaf, 0xd7, 0xbb, 0xd0, 0x76, 0x4e, 0xdc, 0x89, 0x6d, 0x8d,
	0xb5, 0x2d, 0x5d, 0x05, 0x79, 0x6c, 0x5b, 0xaf, 0x6c, 0x4d, 0x30, 0xff, 0x88, 0xd0, 0xf5, 0x49,
	0x38, 0x7d, 0x47, 0x92, 0x42, 0x04, 0x66, 0x72, 0x22, 0xac, 0x3d, 0xb7, 0x12, 0x61, 0x0f, 0x94,
	0x34, 0x4b, 0xa2, 0xe5, 0x19, 0x4a, 0xa0, 0xba, 0xcc, 0x2a, 0x80, 0xca, 0x4d, 0xa0, 0xca, 0xa5,
	0x40, 0xdb, 0x4d, 0xa0, 0x5c, 0x0b, 0x9b, 0x81, 0x52, 0x89, 0x76, 0x2a, 0x40, 0x0b, 0x89, 0x55,
	0x4e, 0xe2, 0x12, 0x32, 0xdc, 0x00, 0xf2, 0xfd, 0x12, 0x32, 0x80, 0x42, 0x21, 0xd7, 0x19, 0x87,
	0xd0, 0x65, 0x14, 0x0a, 0xc4, 0x1c, 0x26, 0xa1, 0x81, 0xa9, 0x28, 0x48, 0xe4, 0x0a, 0xaa, 0x36,
	0x21, 0xd5, 0x9b, 0x30, 0x3f, 0x81, 0x8a, 0xf3, 0x8c, 0x17, 0xf0, 0xc3, 0x2e, 0xd4, 0x86, 0xbd,
	0x7a, 0xb9, 0x78, 0xe5, 0xe5, 0xd2, 0x95, 0x97, 0xb7, 0x1a, 0x97, 0xff, 0x12, 0x40, 0xc5, 0x2f,
	0xa6, 0xb8, 0xbd, 0xfc, 0x9c, 0x84, 0xda, 0xe7, 0xc4, 0x57, 0x26, 0x6e, 0xac, 0x4c, 0xba, 0xb2,
	0xb2, 0x56, 0xb5, 0x32, 0xf6, 0x29, 0x39, 0xab, 0x05, 0x0e, 0xd0, 0x8e, 0xcb, 0x79, 0x6a, 0x95,
	0x2b, 0x8d, 0xca, 0x7f, 0x8a, 0xf4, 0xd2, 0x55, 0x92, 0xe6, 0xca, 0xec, 0x83, 0x9a, 0x5b, 0xeb,
	0xda, 0xd7, 0x8e, 0x7f, 0x42, 0xb7, 0x07, 0xca, 0x20, 0x21, 0xb3, 0x28, 0xc3, 0xb2, 0x45, 0x97,
	0x59, 0x34, 0xf7, 0x38, 0x5e, 0x25, 0x58, 0xb2, 0xe8, 0xe2, 0x59, 0x7f, 0x56, 0x0e, 0xb8, 0x82,
	0x53, 0x77, 0x8f, 0x9f, 0xba, 0x75, 0x95, 0x9b, 0xe7, 0xbb, 0x7d, 0xd9, 0x7c, 0xe3, 0x28, 0x77,
	0x70, 0x95, 0xe0, 0xd9, 0x7c, 0x58, 0x8e, 0x6c, 0x07, 0x5a, 0xa7, 0x63, 0xcb, 0xc9, 0x07, 0x76,
	0x78, 0x32, 0x72, 0x5e, 0x6a, 0x02, 0x75, 0x0e, 0x4f, 0x1c, 0x5b, 0x13, 0xcd, 0x2f, 0x12, 0xa8,
	0xde, 0x34, 0x4e, 0x48, 0x21, 0x2d, 0x1a, 0x9c, 0xb4, 0x85, 0x5d, 0xdb, 0xde, 0x62, 0x63, 0x7b,
	0x57, 0xd8, 0x4a, 0x75, 0xb6, 0x26, 0x6c, 0x4f, 0xa2, 0x59, 0x46, 0x92, 0x05, 0xbe, 0x90, 0xd1,
	0xaa, 0xf8, 0x68, 0x8e, 0xbd, 0xe4, 0x72, 0x72, 0x76, 0x15, 0x1f, 0xad, 0x22, 0x48, 0x57, 0xe1,
	0x3c, 0xcf, 0x50, 0x30, 0x83, 0xf3, 0x70, 0x7a, 0xb4, 0x2b, 0x7a, 0x3c, 0x80, 0x5d, 0x6b, 0x1a,
	0xce, 0xc8, 0x22, 0x9a, 0xb2, 0x78, 0x07, 0xe3, 0x35, 0xaf, 0xfe, 0xb4, 0xb6, 0xd5, 0xf7, 0x2b,
	0x5b, 0xbd, 0x00, 0x75, 0xfd, 0x4e, 0xaf, 0x8e, 0x61, 0x8f, 0xdf, 0x20, 0x81, 0x83, 0xec, 0xb7,
	0x4a, 0x15, 0x04, 0xf3, 0x87, 0x00, 0xff, 0x31, 0x94, 0xdc, 0xb4, 0x1e, 0x82, 0x56, 0x71, 0xae,
	0x55, 0x69, 0xf8, 0x6f, 0xa9, 0xce, 0x75, 0x0b, 0xe0, 0x35, 0x80, 0x13, 0x67, 0xd1, 0x34, 0xaf,
	0xeb, 0x7f, 0x90, 0xfd, 0x28, 0x9b, 0x13, 0xf6, 0x7f, 0x92, 0x1b, 0x94, 0x7c, 0x9e, 0xc3, 0xf6,
	0x1a, 0xb3, 0xae, 0xdb, 0x6c, 0x87, 0x2f, 0x40, 0x2d, 0x37, 0x2e, 0x9d, 0xd1, 0xc0, 0x09, 0x3c,
	0x4a, 0x67, 0x1b, 0xda, 0xbe, 0x6d, 0x0d, 0x8e, 0x6d, 0x57, 0xfb, 0xea, 0x50, 0xcb, 0xf3, 0x83,
	0xa1, 0xed, 0xf8, 0xda, 0x37, 0x47, 0x07, 0x90, 0xad, 0xe1, 0x64, 0xe4, 0x68, 0xdf, 0x9d, 0x37,
	0x0a, 0xfe, 0x4d, 0x3d, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x4c, 0x81, 0xca, 0x61, 0x09,
	0x00, 0x00,
}
