# db info
[GradeManagerDB]
Host="xxxxxx"
Port=3306
User="xxxxxx"
Password="xxxxxx"
DataBaseName="xxxxxx"

[Alarm]
Url="https://sc.ftqq.com/xxxxxx.send"

[IpToAddr]
Key="xxxxxx"
SK="xxxxxx"
Url="xxxxxx"
Path="xxxxxx"

[LocationToAddr]
Key="xxxxxx"
SK="xxxxxx"
Url="xxxxxx"
Path="xxxxxx"
